### ISSUE TITLE
Part 3 

### ISSUE THREAD

**Issue by kiro112** [austinlyons/react-nodejs-tutorial#1]
Error 1

```
babel components -d es5-lib
SyntaxError: components/ReactApp.jsx: Unexpected token (47:3)
  45 |  render() {
  46 |      return (
> 47 |          <div id="app" style={styles.container}>
     |    ^
  48 |              <h1 style={styles.header}>Format & Validate JSON</h1>
  49 |              <p style={styles.error}>{this.state.error}</p>
  50 |              <textarea
```

fixed by Adding .babelrc

```
{
    presets: ["es2015", "react"]
}
```

Error 2
successfully tanspiled with webpack and babel
But gives error
run server via "node server.js"
gives

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (/home/kiro0012/workspace-web/react-node/node_modules/fbjs/lib/invariant.js:39:15)
    at instantiateReactComponent (/home/kiro0012/workspace-web/react-node/node_modules/react/lib/instantiateReactComponent.js:64:134)
    at /home/kiro0012/workspace-web/react-node/node_modules/react/lib/ReactServerRendering.js:41:31
    at ReactServerRenderingTransaction.Mixin.perform (/home/kiro0012/workspace-web/react-node/node_modules/react/lib/Transaction.js:136:20)
    at Object.renderToString (/home/kiro0012/workspace-web/react-node/node_modules/react/lib/ReactServerRendering.js:40:24)
    at /home/kiro0012/workspace-web/react-node/server.js:15:35
    at Layer.handle [as handle_request] (/home/kiro0012/workspace-web/react-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kiro0012/workspace-web/react-node/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/kiro0012/workspace-web/react-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/kiro0012/workspace-web/react-node/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by kiro112** [comment]
Fixed by Changing this

```
export default class ReactApp extends Component {
}
```

to

```
class ReactApp Extends Component { }

module.exports = ReactApp;
```
